Repository FRONT-END-BOOTCAMP-PLUS-3/angry_marimo, pull requests merged in 2025-02, with the labels that each got.

#13 ✨ 워커 기능 구현 완료 !!
  __tests__/components/trash/worker.e2e-spec.ts
  __tests__/public/worker.spec.ts
  app/page.tsx
  components/trash/trash-component.tsx
  components/trash/trash.module.css
  hooks/useInterval.ts
  public/images/trash_level1.png
  public/images/trash_level2.png
  public/images/trash_level3.png
  public/utils/level-image.ts
  public/utils/random-location.ts
  public/workers/trash-worker.ts
  stores/trash-store.ts
  stores/use-store.ts
Labels: Feature, Component, Util

#18 ✨ : 헤더 컴포넌트를 구현하였습니다!
  __tests__/api/logout/route.spec.ts
  __tests__/components/get-user/index.e2e-spec.ts
  __tests__/components/header/dropdown.e2e-spec.ts
  __tests__/components/header/horizontal-logo.e2e-spec.ts
  __tests__/pages/login/actions/user-login.spec.ts
  app/(main)/layout.tsx
  app/(main)/page.module.css
  app/(main)/page.tsx
  app/(main)/pay/_components/pay-form.tsx
  app/api/logout/route.ts
  app/globals.css
  app/layout.tsx
  components/get-user/index.tsx
  components/header/dropdown.module.css
  components/header/dropdown.tsx
  components/header/horizontal-logo.module.css
  components/header/horizontal-logo.tsx
  components/header/index.module.css
  components/header/index.tsx
Labels: Feature, Component

#19 #6 feedback_ 생성 완료!!
  __tests__/components/feedback-btn/feedback-btn.e2e-spec.ts
  app/layout.tsx
  components/feedback-btn/feedback-btn.module.css
  components/feedback-btn/feedback-btn.tsx
  constants/feedback.ts
Labels: Component
